---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    - block:
        - name: Populate instance config
          set_fact:
            instance_conf: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
            skip_instances: false
      rescue:
        - name: Populate instance config when file missing
          set_fact:
            instance_conf: {}
            skip_instances: true

    - name: Destroy molecule instance(s)
      ec2:
        state: absent
        instance_ids: "{{ item.instance_ids }}"
      register: server
      with_items: "{{ instance_conf }}"
      when: not skip_instances

    - name: Destory EIP
      ec2_eip:
        device_id: "{{ item.eni0_id }}"
        ip: "{{ item.address }}"
        in_vpc: true
        state: absent
      with_items: "{{ instance_conf }}"

    - name: Destroy network interface - 0
      ec2_eni:
        eni_id: "{{ item.eni0_id }}"
        state: absent
      with_items: "{{ instance_conf }}"

    - name: Destroy network interface - 1
      ec2_eni:
        eni_id: "{{ item.eni1_id }}"
        state: absent
      with_items: "{{ instance_conf }}"

    # Mandatory configuration for Molecule to function.

